version: "3.3"

volumes:
  redis_data:

networks:
  default:
    driver: bridge

services:
  rest:
    image: davidafsilva/kussx
    ports:
      - 80:8080
    environment:
      KUSSX_REDIS_HOST: redis
    links:
      - redis
  redis:
    image: redis
    volumes:
      - redis_data:/data


